### ISSUE TITLE
model conflicts in branches

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#131]
### **Assumptions**

* A conflict can have N changes as conflicting
  * N branches diverging leads to N changes that are conflicting with each other
  * A conflict edge will be created for every child change of an already existing conflict (leading to N edges)
* conflict edges should be garbage collected
  * Change A and B conflict. A get's a child change C. C is conflicting with B (just like A), insert a new edge for C and remove A.
* N changes can have N conflicts (not to be confused with edges)
  * entity divergence conflict
  * multiple plugin reported conflicts
  * requires `conflict.key` property to identify if a conflict for the reported conflict already exists

**Todos**

- [X] prevent duplicate conflicts
  - [X] ensure that branch A -> merged into -> B points to the same conflict as branch B -> merge into -> A
- [X] ensure that conflict resolution is shared between branches
- [ ] UI to resolve conflicts
- [X] introduce branch pointers for conflicts
- [ ] test conflict resolution for new conflicts
- [X] garbage collect outdated conflicts (happens if a change has a new child)
- [ ] raise conflicts on change sets

**Insights (while implementing)**

* conflict resolution can be N not only 1
  * a conflict between 10 changes might be resolved by keeping 5 changes and discarding the other 5 (that's a resolution with N changes)
* conflicts are a computed result of moving branch pointers (!)
  * if branch pointers move, existing conflicts are invalided

**Notes for loom**

1. conflicts are detected
2. conflicts are direction in-dependent (merge from A to B is identical to B to A)
3. updating the branch change pointer leads to new conflicts

* ⚠️ model of conflicts only arising when merging doesn't make sense
  * old conflicts become irrelevant
  * conflicts should always be re-computed as the branch moves forward
  * 💡 conflicts are computed between two branches. if the branch pointers update, the conflicts are re-computed

**Comment by samuelstroschein** [comment]
likely schema

```typescript
  CREATE TABLE IF NOT EXISTS conflict (
    id: string PRIMARY KEY DEFAULT (uuid_v4()),

    change_a_id TEXT NOT NULL,
    change_b_id TEXT NOT NULL,

    CHECK (change_a_id < change_b_id)
  ) strict;

  CREATE TABLE IF NOT EXISTS conflict_resolution (
    conflict_id TEXT NOT NULL
  ) strict;
```

**Comment by samuelstroschein** [comment]
**Conflicts are likely the computed result of conflicts between two branches but not static (!)**

if true, then:

* lix needs to store merge intents 
* merge intents are used to compute conflicts between two branches on every change 
* users can remove merge intents which will stop computing conflicts

[Are conflicts the computed result between two branches?](https://www.loom.com/share/e17e3026d58f4dd7b03b905c7c012de9?sid=825c5f96-75f4-479f-931d-cd1332d5f675)
