### ISSUE TITLE
follow up of change queue rework

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#139]
### Context

Follow up of [LIXDK-102](https://linear.app/opral/issue/LIXDK-102/remove-file-internal-in-favor-of-simplified-change-queue).

### Tasks

- [X] pass before and after metadata state to detectChanges (in case the metadata changed)
- [X] rename instruction flag to `$skip_change_queue`
- [X] hide instruction from ts type

[LIXDK-120](https://linear.app/opral/issue/LIXDK-120/extract-change-queue-from-openlix)
