### ISSUE TITLE
introduce accounts

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#144]
### Context

Lix apps like the file manager want to query "who did this change" and related queries.

### Proposal

Introduce accounts.

### Tasks

[LIXDK-124](https://linear.app/opral/issue/LIXDK-124/multi-author-support)

- [X] account table
- [X] default anonymous account to enable "non logged in" trying out of lix
- [X] `switchAccounts(lix)` api
- [X] `currentAccounts(lix)` api
