### ISSUE TITLE
query server, local mutation log

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#147]
### Context

We can simplify sync by performing select queries against the server (if sync is on), mutations locally that are stored in a log, and then sync the mutation log. If the mutation log leads to conflicts, the client is moved to a different version. 

* (+) not having to deal with stale data because select is performed against server
* (+) can be incrementally extended with cache, etc
* (+) avoids diffing 
* (+) lazy loading out of the box

* (o) requires order independence of mutations which is given  

* (-) mutation logs can become large of clients that have been offline for a long time  

### Tasks

- [ ] execute queries against server when sync is on
- [ ] local mutation log 
- [ ] sync mutation log with server 
  - [ ] check for conflicts locally 
  - [ ] send mutation log to server
  - [ ] apply mutation log on server
  - [ ] if conflicts detected in mutation log, create new version on client

**Comment by samuelstroschein** [comment]
cancelled in favor of @martin.lysk1's clock approach. 

* no mutation log 
* no queue that the server needs to coordinate
* client keeps querying locally
