### ISSUE TITLE
naive poll based sync

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#152]
### Context

To keep things simpler than [LIXDK-240](https://linear.app/opral/issue/LIXDK-240/query-server-local-mutation-log), @martin.lysk1 and I decided to go with clocks that report what rows are missing on both server and client.

As the first implementation step, the client and server naively sent all rows over the wire to test if the sync mechanism will work. Afterwards, what rows are sent over the wire can be optimized e.g. via clocks.

### Goal

Have a working sync prototype.

### Non-goals

Implement any optimizations (like clocks).

### Tasks

- [X] client sends server all rows that should be synced periodically
- [X] server applies rows
- [X] handle jsonb in snapshot content
- [X] client polls server for rows to be synced
- [ ] client detects conflicts in rows from server
- [ ] intialize init sync process in openlix
