### ISSUE TITLE
immutable change sets

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#155]
### Context

For syncing, change sets need to be immutable. 

### Tasks

- [ ] version pointer update creates new change sets
- [ ] update change set creates a new change set and updates references to the change set
- [ ] throw when updating a change set && change set element

**Comment by samuelstroschein** [comment]
cancelled in favor of [LIXDK-251](https://linear.app/opral/issue/LIXDK-251/de-couple-versions-from-change-set-table)
