### ISSUE TITLE
implement sync in csv app

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#166]
### Context

We need to implement sync in the csv app to test it.

### Tasks

- [X] implement `init-sync-process`
- [X] call `init-sync-process` in `openLixInMemory`
- [X] apply changes on pulling changes
