### ISSUE TITLE
extend demo with salary csv

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#229]
### Context

The newsletter csv is too simple to show off change control, the cap-table example too niche. 

### Proposal

Have a salary csv example to show off 

* "who changed the salary of person X"
* "why was the salary changed?"
* "automations based on salary change"

### Tasks

- [ ] create salary example csv
- [ ] initial confirm changes
- [ ] fill the demo lix with existing changes
