### ISSUE TITLE
Add `DetectedChange.schema`

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#37]
### Context

Add `plugin.schema: JSONSchema` for runtime reflection of the types and runtime validation (ensuring that the history is not broken?

**Pros**

* switching from one plugin to another that uses the same schema becomes possible
* lix can validate the snapshots, ensuring that the history always obeys to the schema
* lix can use the schema information for diffing only snapshots (instead of entire files)

### Tasks

- [X] add plugin.`detectedChange.schema`
- [ ] store the `detectedChange.schema` in a `schema` table to never loose a schema of a change
  - [ ] throw if detected schema key exists and the schema differs
- [X] add `change.schema_key`

[LIXDK-106](https://linear.app/opral/issue/LIXDK-106/remove-changeplugin-key-and-add-changeschema) because we don't need it to query for apply changes anymore. if we need it, we can add it again in the future

**Comment by samuelstroschein** [comment]
If [https://github.com/opral/lix-sdk/issues/42](https://github.com/opral/lix-sdk/issues/42) is accepted, the schema would be `payloadSchema` without the nesting of types. 

Here is an example payload schema for the inlang plugin if [LIX-109](https://linear.app/opral/issue/LIX-109/merge-changevalue-and-changemeta-changepayload) is accepted.

```
const plugin = {
  payloadKey: "inlang",
  payloadSchema: {
    snapshot: [bundle, bundleV2, message, variant]
  }
}
```

**Comment by samuelstroschein** [comment]
The schema key doesn't seem to be needed. The `type` can point to schema information. 

The current proposal proposes a schema key that points to a schema with multiple types. What if we simply define `type` as "you point to a type"? 

* removes a redundant property (disk space, simpler explainability, etc.) 
* de-couples schema definitions from a plugin 
  * plugins can share types 
  * potential other benefits
* de-couples type information (which can be retrieved from the schema)

```diff
id: "change2",
file_id: "mock",
-schema_key: "opral-csv",
-type: "cell"
+schema: "opral-csv-cell",
```

**Comment by samuelstroschein** [comment]
Sync with @martin.lysk1: 

* keep plugin_key
* replace `type` with `schema` makes sense
* needs additional schema table with foreign key to change table

**Comment by samuelstroschein** [comment]
We should likely add `change.schema_id` instead of `change.schema_key` and have a relational table where we store all schemas to: 

* prevent the loss of schema information with foreign key constraints
* two schemas with the same key don't interfer with each other because the schema id is generated from a hash.

**Comment by samuelstroschein** [comment]
The API is also not `plugin.schema` but the `DetectedChange` should have a `schema` property. 

1. Every change that get's reported, has a schema. 
2. The schema is stored by lix and immutable (like changes)

**Comment by samuelstroschein** [comment]
could be so minimal as 

```typescript
schema: {
	type: "json",
	key: "samuel-scool-csv-column-cell-v1",
},
```
