### ISSUE TITLE
don't overwrite draft changes

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#61]
### Context

Lix is overwriting uncommitted changes.

Overwriting uncommitted changes has been introduced because a concept of [LIX-126](https://linear.app/opral/issue/LIX-126/sequence-branching) was missing. If user A changes cell 45, a change is created. If user A changes cell 45 again, the old change is overwritten.

The concept of "one draft change at a time for a given entity" is problematic:

* High potential to corrupting lix.
* Requires users to commit changes ([LIX-125](https://linear.app/opral/issue/LIX-125/whats-the-purpose-of-a-commit)) to collaborate.
  * Assume that user A made a change to cell 45 and user B made a change to c45. Both have not committed their changes. Either user A's change will overwrite user B's change, or vice versa.
  * Live collaboration requires collaboration without commits.
* An undo stack is easy to implement if we don't overwrite changes [LIX-96](https://linear.app/opral/issue/LIX-96/is-a-undo-stack-for-workingdraft-changes-wanted)

[Draft Changes and Collaboration Strategies 📝](https://www.loom.com/share/9d49d1368e564f06bc346a35b4f5a78f?sid=f95d607e-0ed8-4bfe-8f35-e021bd139cdc)

### Proposal

Don't overwrite draft changes to enable collaboration without commits.

* It's one of gits largest annoyances that every tiny typo needs to be committed to collaborate with others. 
* There are many scenarios where sharing draft changes is desireable. Working with a host that syncs, live collaboration, sharing the draft of a legal document with a collegue etc.

### Tasks

- [ ] Expose a `lastDraftChange` utility query for apps to get a filtered history that only shows committed changes
- [ ] Expose `squashAndCommitLastDraftChange` utility for testing
- [x] Don't overwrite draft changes

**Comment by samuelstroschein** [comment]
cc @niklas.buchfink @nils.jacobsen

**Comment by samuelstroschein** [comment]
If things don't work out, we can revert back to "one draft change at a time" but I doubt that the UX is better and risk of corrupting lix remains high.

**Comment by samuelstroschein** [comment]
Will probably implement this next week.

**Comment by samuelstroschein** [comment]
@niklas.buchfink just found another bug due to overwriting draft changes. 

if a conflict is raised to to a merge but the conflicting change was a draft change that has been deleted, lix crashes.  

[Resolving conflicts by deleting my own change?](https://www.loom.com/share/695389809356492ea381c31b968db184?sid=ff682f14-81f4-4f19-92e2-03c495e04925)

making "draft" changes immutable too resolves the crash. how the ux of a conflicting change that has been "deleted" is shown is another question. probably by not displaying the conflict in the current sequence ([LIX-126](https://linear.app/opral/issue/LIX-126/sequence-branching)). 

adding foreign key constraints will also avoid crashes [LIX-134](https://linear.app/opral/issue/LIX-134/add-foreign-key-constraints)

**Comment by samuelstroschein** [comment]
Definite confirmation that forcing commits is wrong. Just experienced this with the csv prototype [https://www.loom.com/share/2762a4d8ee9d422f8de0466c70c95514?sid=15c2d77b-10c5-4763-8775-d2ceb812a8c6](https://www.loom.com/share/2762a4d8ee9d422f8de0466c70c95514?sid=15c2d77b-10c5-4763-8775-d2ceb812a8c6)

**Comment by samuelstroschein** [comment]
Yes, I think we are expressing different intents with the download button. I suggest to build [LIXDK-126](https://linear.app/opral/issue/LIXDK-126/branching) to then work on [LIXDK-115](https://linear.app/opral/issue/LIXDK-115/mergepreviewchange-proposals). We should be aligned with an an official concept for opening change proposals

**Comment by samuelstroschein** [comment]
We agreed to unbundle this issue from [LIXDK-126](https://linear.app/opral/issue/LIXDK-126/branching) to unblock [LIXDK-158](https://linear.app/opral/issue/LIXDK-158/introduce-changetag-to-filter-history-and-replace-the-purpose-of). <br><br>see [https://discord.com/channels/897438559458430986/1283386433817677855/1283508975198802004](https://discord.com/channels/897438559458430986/1283386433817677855/1283508975198802004)
