### ISSUE TITLE
telemetry

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#73]
### Context

We need telemetry insights for lix. 

### Tasks

- [ ] add lix ids
  - [ ] `lix/.id` id file
  - [ ] `lix.id.get()`

- [ ] `LIX-SDK loaded`  event similar to `INLANG-SDK loaded`
  - [ ] number_of_changes
  - [ ] size (sqlite file size)
  - [ ] file_extensions: `{'csv': 5, 'sqlite': 3, 'md': 2}`
  - [ ] plugins
  - [ ] app_id (for simply breakdown)
- [ ] `INLANG-SDK loaded` add `lix_id` property
- [ ] posthog: change ecosystem insights to `LIX-SDK loaded`
