### ISSUE TITLE
remove commits

### ISSUE THREAD

**Issue by samuelstroschein** [opral/lix-sdk#75]
### Context

Commits have no use anymore after unbundling them into three different intents (see [LIXDK-125](https://linear.app/opral/issue/LIXDK-125/whats-the-purpose-of-a-commit)):

1. [LIXDK-147](https://linear.app/opral/issue/LIXDK-147/change-discussions) 
2. [MESDK-234](https://linear.app/opral/issue/MESDK-234/introduce-changetag-to-filter-history-and-replace-the-purpose-of) 
3. Commits were never used for merging or branching

### Task 

Remove commits from lix. 

- [ ] remove change.commit_id
- [ ] remove commit table
- [ ] remove `lix.commit`

**Comment by NilsJacobsen** [comment]
Let @niklas.buchfink and me know when we do that step, so we deal with it in the frontend correctly
